### ISSUE TITLE
Getting image from camera

### ISSUE THREAD

**Issue by aazizyan** [freeuni-sdp/iot-camera-object-recognizer#1]
@gkiko კამერიდან სურათს როგორც byte array-ს მივიღებთ თუ path, რომლიდანაც შევძლევთ გადმოწერას ?

**Comment by gkiko** [comment]
ბაიტების სტრიმს მიიღებ

**Comment by aazizyan** [comment]
@gkiko სუფთა ბაიტების სტრიმია, თუ რამე ჰედერებიც ექნება ?

**Comment by gkiko** [comment]
http ჰედერი. არაფერი განსაკუთრებული
